name: "CI - Nix"

on:
  push:
    branches:
    - main
    - devel
  pull_request:
    branches:
    - main
    - devel

jobs:
  nix:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: gepetto
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: ros
      - run: nix build -L --cores 1 --max-jobs 1 --show-trace
